//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurigma.PhotoKiosk.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aurigma.PhotoKiosk.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Kiosk.
        /// </summary>
        internal static string BluetoothHostNameDefValue {
            get {
                return ResourceManager.GetString("BluetoothHostNameDefValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, pay for the order and get back..
        /// </summary>
        internal static string CDBurningPaymentInstructions {
            get {
                return ResourceManager.GetString("CDBurningPaymentInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoKiosk.config.
        /// </summary>
        internal static string ConfigFileName {
            get {
                return ResourceManager.GetString("ConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurigma.PhotoKiosk.Core.CropEN.xml.
        /// </summary>
        internal static string CropFile {
            get {
                return ResourceManager.GetString("CropFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop mode.
        /// </summary>
        internal static string CropModeTag {
            get {
                return ResourceManager.GetString("CropModeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer email.
        /// </summary>
        internal static string CustomerEmailTag {
            get {
                return ResourceManager.GetString("CustomerEmailTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        internal static string CustomerNameTag {
            get {
                return ResourceManager.GetString("CustomerNameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer phone.
        /// </summary>
        internal static string CustomerPhoneTag {
            get {
                return ResourceManager.GetString("CustomerPhoneTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateTag {
            get {
                return ResourceManager.GetString("DateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Kiosk .
        /// </summary>
        internal static string EventLogSourceName {
            get {
                return ResourceManager.GetString("EventLogSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string FilenameTag {
            get {
                return ResourceManager.GetString("FilenameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string FormatTag {
            get {
                return ResourceManager.GetString("FormatTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoKiosk.chm.
        /// </summary>
        internal static string HelpFile {
            get {
                return ResourceManager.GetString("HelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurigma\Photo Kiosk.
        /// </summary>
        internal static string InstallPath {
            get {
                return ResourceManager.GetString("InstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk ID.
        /// </summary>
        internal static string KioskIdTag {
            get {
                return ResourceManager.GetString("KioskIdTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurigma\Photo Kiosk\.
        /// </summary>
        internal static string LicenseKeyPath {
            get {
                return ResourceManager.GetString("LicenseKeyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        internal static string OrderIdTag {
            get {
                return ResourceManager.GetString("OrderIdTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper type.
        /// </summary>
        internal static string PaperTypeTag {
            get {
                return ResourceManager.GetString("PaperTypeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, pay for the order and get back..
        /// </summary>
        internal static string PhotoPrintingPaymentInstructions {
            get {
                return ResourceManager.GetString("PhotoPrintingPaymentInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurigma.PhotoKiosk.Core.PriceEN.xml.
        /// </summary>
        internal static string PriceFile {
            get {
                return ResourceManager.GetString("PriceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints quantity.
        /// </summary>
        internal static string PrintsQuantityTag {
            get {
                return ResourceManager.GetString("PrintsQuantityTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurigma.PhotoKiosk.Core.ReceiptTemplateEN.xaml.
        /// </summary>
        internal static string ReceiptFile {
            get {
                return ResourceManager.GetString("ReceiptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurigma.PhotoKiosk.Core.ResourcesEN.xml.
        /// </summary>
        internal static string ResourcesFile {
            get {
                return ResourceManager.GetString("ResourcesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurigma.PhotoKiosk.Core.TransformEN.xslt.
        /// </summary>
        internal static string TransformFile {
            get {
                return ResourceManager.GetString("TransformFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurigma\PhotoKiosk\.
        /// </summary>
        internal static string UserConfigPath {
            get {
                return ResourceManager.GetString("UserConfigPath", resourceCulture);
            }
        }
    }
}
