//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurigma.PhotoKiosk.ConfigurationTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aurigma.PhotoKiosk.ConfigurationTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot construct Photo Kiosk activation code ({0})..
        /// </summary>
        internal static string ActivationCodeError {
            get {
                return ResourceManager.GetString("ActivationCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Services Screen.
        /// </summary>
        internal static string AdditionalServicesScreen {
            get {
                return ResourceManager.GetString("AdditionalServicesScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth folder does not exist..
        /// </summary>
        internal static string BluetoothFolderError {
            get {
                return ResourceManager.GetString("BluetoothFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth host cannot be an empty string..
        /// </summary>
        internal static string BluetoothHostError {
            get {
                return ResourceManager.GetString("BluetoothHostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD\DVD Burning Screen.
        /// </summary>
        internal static string BurningScreen {
            get {
                return ResourceManager.GetString("BurningScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback file does not exist..
        /// </summary>
        internal static string CallbackFileError {
            get {
                return ResourceManager.GetString("CallbackFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel with the same name already exists..
        /// </summary>
        internal static string ChannelError {
            get {
                return ResourceManager.GetString("ChannelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Upload Way Screen.
        /// </summary>
        internal static string ChooseUploadWayScreen {
            get {
                return ResourceManager.GetString("ChooseUploadWayScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Order Screen.
        /// </summary>
        internal static string ConfirmOrderScreen {
            get {
                return ResourceManager.GetString("ConfirmOrderScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info Screen.
        /// </summary>
        internal static string ContactInfoScreen {
            get {
                return ResourceManager.GetString("ContactInfoScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the same crop format.
        /// </summary>
        internal static string CopyToCrops {
            get {
                return ResourceManager.GetString("CopyToCrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop formats file does not exist..
        /// </summary>
        internal static string CropFileError {
            get {
                return ResourceManager.GetString("CropFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop format with the same name already exists..
        /// </summary>
        internal static string CropFormatDuplicateError {
            get {
                return ResourceManager.GetString("CropFormatDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop format name cannot be an empty string..
        /// </summary>
        internal static string CropFormatEmptyError {
            get {
                return ResourceManager.GetString("CropFormatEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop height cannot be less than 0..
        /// </summary>
        internal static string CropHeightError {
            get {
                return ResourceManager.GetString("CropHeightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read crop formats file. 
        ///{0}.
        /// </summary>
        internal static string CropReadingError {
            get {
                return ResourceManager.GetString("CropReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop width cannot be less than 0..
        /// </summary>
        internal static string CropWidthError {
            get {
                return ResourceManager.GetString("CropWidthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order store path does not exist..
        /// </summary>
        internal static string DestinationPathError {
            get {
                return ResourceManager.GetString("DestinationPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc label cannot be an empty string..
        /// </summary>
        internal static string DiscLabelError {
            get {
                return ResourceManager.GetString("DiscLabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be in range [{0}, {1}]..
        /// </summary>
        internal static string DiscountValueOutOfRangeError {
            get {
                return ResourceManager.GetString("DiscountValueOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be greater or equal than {0}..
        /// </summary>
        internal static string DiscountValueToBigError {
            get {
                return ResourceManager.GetString("DiscountValueToBigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be positive integer..
        /// </summary>
        internal static string DiscountValueToLessError {
            get {
                return ResourceManager.GetString("DiscountValueToLessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop format cannot contain zero and non-zero parameters at the same time..
        /// </summary>
        internal static string FreeCropError {
            get {
                return ResourceManager.GetString("FreeCropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper format cannot contain zero and non-zero parameters at the same time..
        /// </summary>
        internal static string FreeFormatError {
            get {
                return ResourceManager.GetString("FreeFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height ({0}).
        /// </summary>
        internal static string HeightColumnHeader {
            get {
                return ResourceManager.GetString("HeightColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Editor Screen.
        /// </summary>
        internal static string ImageEditorScreen {
            get {
                return ResourceManager.GetString("ImageEditorScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivity timeout should be greater than 0..
        /// </summary>
        internal static string InactivityTimeoutError {
            get {
                return ResourceManager.GetString("InactivityTimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inches.
        /// </summary>
        internal static string inch {
            get {
                return ResourceManager.GetString("inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Instant).
        /// </summary>
        internal static string InstantPostfix {
            get {
                return ResourceManager.GetString("InstantPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license key has wrong format..
        /// </summary>
        internal static string KeyIsInvalid {
            get {
                return ResourceManager.GetString("KeyIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization file does not exist..
        /// </summary>
        internal static string LocalizationFileError {
            get {
                return ResourceManager.GetString("LocalizationFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory cache size should be greater than 0..
        /// </summary>
        internal static string MemoryCacheSizeError {
            get {
                return ResourceManager.GetString("MemoryCacheSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum price ({0}):.
        /// </summary>
        internal static string MinimumPriceLabel {
            get {
                return ResourceManager.GetString("MinimumPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string mm {
            get {
                return ResourceManager.GetString("mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Forming Screen.
        /// </summary>
        internal static string OrderFormingScreen {
            get {
                return ResourceManager.GetString("OrderFormingScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID Screen.
        /// </summary>
        internal static string OrderIdScreen {
            get {
                return ResourceManager.GetString("OrderIdScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read Order Manager configuration. 
        ///{0}.
        /// </summary>
        internal static string OrderManagerConfigError {
            get {
                return ResourceManager.GetString("OrderManagerConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format resolution should be greater than 0..
        /// </summary>
        internal static string PaperDpiError {
            get {
                return ResourceManager.GetString("PaperDpiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper format with the same name already exists..
        /// </summary>
        internal static string PaperFormatDuplicateError {
            get {
                return ResourceManager.GetString("PaperFormatDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper format name cannot be an empty string..
        /// </summary>
        internal static string PaperFormatEmptyError {
            get {
                return ResourceManager.GetString("PaperFormatEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper height should be greater than 0..
        /// </summary>
        internal static string PaperHeightError {
            get {
                return ResourceManager.GetString("PaperHeightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper type with the same name already exists..
        /// </summary>
        internal static string PaperTypeDuplicateError {
            get {
                return ResourceManager.GetString("PaperTypeDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper type name cannot be an empty string..
        /// </summary>
        internal static string PaperTypeEmptyError {
            get {
                return ResourceManager.GetString("PaperTypeEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper width should be greater than 0..
        /// </summary>
        internal static string PaperWidthError {
            get {
                return ResourceManager.GetString("PaperWidthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read Photo Kiosk configuration. 
        ///{0}.
        /// </summary>
        internal static string PhotoKioskConfigError {
            get {
                return ResourceManager.GetString("PhotoKioskConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo template should ends with &quot;{0}&quot;.
        /// </summary>
        internal static string PhotoTemplateError {
            get {
                return ResourceManager.GetString("PhotoTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price should be greater than 0..
        /// </summary>
        internal static string PriceError {
            get {
                return ResourceManager.GetString("PriceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price file does not exist..
        /// </summary>
        internal static string PriceFileError {
            get {
                return ResourceManager.GetString("PriceFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read prices file. 
        ///{0}.
        /// </summary>
        internal static string PriceReadingError {
            get {
                return ResourceManager.GetString("PriceReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to print a receipt.
        ///{0}.
        /// </summary>
        internal static string PrintingError {
            get {
                return ResourceManager.GetString("PrintingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Printing Screen.
        /// </summary>
        internal static string PrintingScreen {
            get {
                return ResourceManager.GetString("PrintingScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Screen.
        /// </summary>
        internal static string ProgressScreen {
            get {
                return ResourceManager.GetString("ProgressScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt template file does not exist..
        /// </summary>
        internal static string ReceiptTemplateError {
            get {
                return ResourceManager.GetString("ReceiptTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop to Fill.
        /// </summary>
        internal static string RecieptTestCropMode {
            get {
                return ResourceManager.GetString("RecieptTestCropMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Doe.
        /// </summary>
        internal static string RecieptTestCustomerName {
            get {
                return ResourceManager.GetString("RecieptTestCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KioskID_123.
        /// </summary>
        internal static string RecieptTestOrderId {
            get {
                return ResourceManager.GetString("RecieptTestOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossy.
        /// </summary>
        internal static string RecieptTestPaperType {
            get {
                return ResourceManager.GetString("RecieptTestPaperType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} registry key cannot be found..
        /// </summary>
        internal static string RegisteryKeyNotFound {
            get {
                return ResourceManager.GetString("RegisteryKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file does not exist..
        /// </summary>
        internal static string ScreenImageError {
            get {
                return ResourceManager.GetString("ScreenImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search process duration should be greater than 0..
        /// </summary>
        internal static string SearchProcessDurationError {
            get {
                return ResourceManager.GetString("SearchProcessDurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folders Screen.
        /// </summary>
        internal static string SelectFoldersScreen {
            get {
                return ResourceManager.GetString("SelectFoldersScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Screen.
        /// </summary>
        internal static string SelectScreen {
            get {
                return ResourceManager.GetString("SelectScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service with the same name already exists..
        /// </summary>
        internal static string ServiceNameDuplicateError {
            get {
                return ResourceManager.GetString("ServiceNameDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name cannot be an empty string..
        /// </summary>
        internal static string ServiceNameEmptyError {
            get {
                return ResourceManager.GetString("ServiceNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license key was successfully registered..
        /// </summary>
        internal static string SuccessfullyRegistered {
            get {
                return ResourceManager.GetString("SuccessfullyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license key was successfully unregistered..
        /// </summary>
        internal static string SuccessfullyUnregistered {
            get {
                return ResourceManager.GetString("SuccessfullyUnregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You Cancel Screen.
        /// </summary>
        internal static string ThankYouCancelScreen {
            get {
                return ResourceManager.GetString("ThankYouCancelScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You Screen.
        /// </summary>
        internal static string ThankYouScreen {
            get {
                return ResourceManager.GetString("ThankYouScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme file does not exist..
        /// </summary>
        internal static string ThemeFileError {
            get {
                return ResourceManager.GetString("ThemeFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the necessary registry rights..
        /// </summary>
        internal static string UnauthorizedAccessError {
            get {
                return ResourceManager.GetString("UnauthorizedAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        internal static string UnitsComboBoxInch {
            get {
                return ResourceManager.GetString("UnitsComboBoxInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeters.
        /// </summary>
        internal static string UnitsComboBoxMm {
            get {
                return ResourceManager.GetString("UnitsComboBoxMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister.
        /// </summary>
        internal static string Unregister {
            get {
                return ResourceManager.GetString("Unregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Photos Screen.
        /// </summary>
        internal static string UploadingPhotosScreen {
            get {
                return ResourceManager.GetString("UploadingPhotosScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was terminated by the user..
        /// </summary>
        internal static string UserCancelsOperation {
            get {
                return ResourceManager.GetString("UserCancelsOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Screen.
        /// </summary>
        internal static string WelcomeScreen {
            get {
                return ResourceManager.GetString("WelcomeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width ({0}).
        /// </summary>
        internal static string WidthColumnHeader {
            get {
                return ResourceManager.GetString("WidthColumnHeader", resourceCulture);
            }
        }
    }
}
